Add logical operators and expressions
bylexus/fparse pull request #57
Opened 2024-08-20 14:51 UTC by LuigiPulcini

This PR adds the possibility of having logical operators and expressions in a formula.

Possible operators are `>`, `<`, `>=`, `<=`, `=` and `!=`, the meaning of which is trivial.

Since the final goal is to use those operators in a mathematical formula, the result of a logical expression will always return a number: either `1` (when the expression is `true`) or `0` (when it is `false`), which can easily be used in a formula to achieve conditional calculations.

An example of a logical expression used in a formula is:

```javascript
const f1 = new Formula( '[price] * ( 1 + 0.25 * ( [weight] > 10 )' );

const res = f1.evaluate( { price: 100, weight: 12.4 } );
console.log( res );

// res = 125
```

This would be essential to implement some logical functions – such as `IF()` – in the same form Microsoft Excel or Google Sheets do:

```javascript
const f1 = new Formula( 'IF( [weight] > 10, 1.25, 1 ) * [price]' );

f1.IF = ( value, ifTrue, ifFalse ) => {
    return value ? ifTrue : ifFalse;
};

const res = f1.evaluate( { price: 100, weight: 12.4 } );
console.log( res );

// res = 125
```

2024-08-20 16:47 UTC, bylexus commented
This is a useful addition, as it opens the possibility to implement conditional logic, thanks.

Would you mind:

- adding some Unit tests (see `spec/specs/` for examples)
- merging the develop branch to resolve merge conflicts

Then I will consider your addition to be merged.

Many thanks for your contribution.

2024-08-20 20:25 UTC, LuigiPulcini commented
Hi, @bylexus,

Thanks for reviewing my PR so swiftly. I followed both of your recommendations. While adding Unit tests, I spotted a few missing declarations for the new Logical Expression, which I added now, and rebuilt all the distribution files.

Let me know if the tests are enough and if there is anything else I can do.

2024-08-24 08:03 UTC, bylexus requested changes
Hello,

Many thanks for your contribution. I have reviewed your input, and think the logical operator precedence should be changed to fit between PowerExpression (strongest), then logical expressions, then the rest. In the actual solution, the logical expressions are the weakest, which is wrong in my opinion.

Let me know what you think.

2024-08-24 08:03 UTC, bylexus commented on src/fparser.ts
> +
See comment above: Please change the order of logical operator precedence to fit between PowerExpression and MultDivExpression:

I think the "correct" or logical precedence of operators is:

    (strongest): Power of (x^y)
    logical operators (x<y)
    multiplication/division
    additon/ substraction

So the following formula:

3+2>1*4<2^3

should be parsed as

3+((2>1)*(4<(2^3)))

2024-08-24 09:56 UTC, bylexus commented on src/fparser.ts
> +
On the other hand, if we look at other programming languages, e.g. JavaScript, the logical operators have the lowest precedence:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table

What do you think, what would be an appropriate handling / precedence? I would recommend to implement the general consensus, as in other languages...

2024-08-24 09:57 UTC, bylexus commented on spec/specs/exprTreeSpec.js
> +        });
On the other hand, if we look at other programming languages, e.g. JavaScript, the logical operators have the lowest precedence:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table

What do you think, what would be an appropriate handling / precedence? I would recommend to implement the general consensus, as in other languages...

2024-08-24 10:15 UTC, bylexus commented
OK, I have decided that your solution and your implementation of the operator precedence is correct. I will merge your contribution into my develop branch, add some documentation and examples, and release a new version.

many thanks for your useful contribution.

2024-08-24 10:18 UTC, merged

2024-08-28 13:14 UTC, LuigiPulcini commented
Thanks for reviewing the PR so thoroughly. I am glad that, in the end, it worked out as intended!